# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/a5ultexx/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/a5ultexx/proprietary/vendor/lib/libsec-ril-dsds.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril-dsds.so \
    vendor/samsung/a5ultexx/proprietary/vendor/lib/libsec-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril.so \
    vendor/samsung/a5ultexx/proprietary/vendor/lib/hw/nfc_nci.msm8916.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/nfc_nci.msm8916.so \
    vendor/samsung/a5ultexx/proprietary/etc/sec_s3fwrn5_rfreg.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/sec_s3fwrn5_rfreg.bin \
    vendor/samsung/a5ultexx/proprietary/vendor/firmware/sec_s3fwrn5_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_s3fwrn5_firmware.bin
